/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colorChanger;

import java.awt.Color;
import java.awt.Component;

/**
 *
 * @author nightsec
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        setExtendedState(MainFrame.NORMAL);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        backgroundChange = new javax.swing.JPanel();
        purpleMainPanel = new javax.swing.JPanel();
        cyanMainPanel = new javax.swing.JPanel();
        orangeMainPanel = new javax.swing.JPanel();
        pinkMainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        purpleSidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cyanSidePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        orangeSidePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pinkSidePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        headerSidePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCHAPP v.0.1");
        setBackground(new java.awt.Color(55, 183, 87));
        getContentPane().setLayout(new java.awt.CardLayout());

        backPanel.setBackground(new java.awt.Color(55, 183, 87));
        backPanel.setName("backPanel"); // NOI18N

        backgroundChange.setBackground(new java.awt.Color(70, 211, 105));
        backgroundChange.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        backgroundChange.setLayout(new java.awt.CardLayout());

        purpleMainPanel.setBackground(new java.awt.Color(217, 103, 208));

        javax.swing.GroupLayout purpleMainPanelLayout = new javax.swing.GroupLayout(purpleMainPanel);
        purpleMainPanel.setLayout(purpleMainPanelLayout);
        purpleMainPanelLayout.setHorizontalGroup(
            purpleMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        purpleMainPanelLayout.setVerticalGroup(
            purpleMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        backgroundChange.add(purpleMainPanel, "card2");

        cyanMainPanel.setBackground(new java.awt.Color(74, 203, 245));

        javax.swing.GroupLayout cyanMainPanelLayout = new javax.swing.GroupLayout(cyanMainPanel);
        cyanMainPanel.setLayout(cyanMainPanelLayout);
        cyanMainPanelLayout.setHorizontalGroup(
            cyanMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        cyanMainPanelLayout.setVerticalGroup(
            cyanMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        backgroundChange.add(cyanMainPanel, "card3");

        orangeMainPanel.setBackground(new java.awt.Color(255, 134, 0));

        javax.swing.GroupLayout orangeMainPanelLayout = new javax.swing.GroupLayout(orangeMainPanel);
        orangeMainPanel.setLayout(orangeMainPanelLayout);
        orangeMainPanelLayout.setHorizontalGroup(
            orangeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        orangeMainPanelLayout.setVerticalGroup(
            orangeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        backgroundChange.add(orangeMainPanel, "card4");

        pinkMainPanel.setBackground(new java.awt.Color(244, 80, 121));

        javax.swing.GroupLayout pinkMainPanelLayout = new javax.swing.GroupLayout(pinkMainPanel);
        pinkMainPanel.setLayout(pinkMainPanelLayout);
        pinkMainPanelLayout.setHorizontalGroup(
            pinkMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        pinkMainPanelLayout.setVerticalGroup(
            pinkMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        backgroundChange.add(pinkMainPanel, "card5");

        sidePanel.setBackground(new java.awt.Color(70, 211, 105));
        sidePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        purpleSidePanel.setBackground(new java.awt.Color(70, 211, 105));
        purpleSidePanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                purpleSidePanelFocusGained(evt);
            }
        });
        purpleSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purpleSidePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purpleSidePanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purpleSidePanelMouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Padauk", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Purple Color");

        javax.swing.GroupLayout purpleSidePanelLayout = new javax.swing.GroupLayout(purpleSidePanel);
        purpleSidePanel.setLayout(purpleSidePanelLayout);
        purpleSidePanelLayout.setHorizontalGroup(
            purpleSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(purpleSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(purpleSidePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        purpleSidePanelLayout.setVerticalGroup(
            purpleSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(purpleSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(purpleSidePanelLayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );

        cyanSidePanel.setBackground(new java.awt.Color(70, 211, 105));
        cyanSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cyanSidePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cyanSidePanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cyanSidePanelMouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Padauk", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Cyan Color");

        javax.swing.GroupLayout cyanSidePanelLayout = new javax.swing.GroupLayout(cyanSidePanel);
        cyanSidePanel.setLayout(cyanSidePanelLayout);
        cyanSidePanelLayout.setHorizontalGroup(
            cyanSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(cyanSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cyanSidePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        cyanSidePanelLayout.setVerticalGroup(
            cyanSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(cyanSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cyanSidePanelLayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        orangeSidePanel.setBackground(new java.awt.Color(70, 211, 105));
        orangeSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orangeSidePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orangeSidePanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orangeSidePanelMouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Padauk", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Orange Color");

        javax.swing.GroupLayout orangeSidePanelLayout = new javax.swing.GroupLayout(orangeSidePanel);
        orangeSidePanel.setLayout(orangeSidePanelLayout);
        orangeSidePanelLayout.setHorizontalGroup(
            orangeSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(orangeSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(orangeSidePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        orangeSidePanelLayout.setVerticalGroup(
            orangeSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(orangeSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(orangeSidePanelLayout.createSequentialGroup()
                    .addGap(0, 9, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        pinkSidePanel.setBackground(new java.awt.Color(70, 211, 105));
        pinkSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinkSidePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pinkSidePanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pinkSidePanelMouseEntered(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(254, 254, 254));
        jLabel4.setFont(new java.awt.Font("Padauk", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Pink Color");

        javax.swing.GroupLayout pinkSidePanelLayout = new javax.swing.GroupLayout(pinkSidePanel);
        pinkSidePanel.setLayout(pinkSidePanelLayout);
        pinkSidePanelLayout.setHorizontalGroup(
            pinkSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pinkSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pinkSidePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pinkSidePanelLayout.setVerticalGroup(
            pinkSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(pinkSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pinkSidePanelLayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        headerSidePanel.setBackground(new java.awt.Color(70, 211, 105));

        jLabel5.setFont(new java.awt.Font("Padauk", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("COLOR CHANGE");

        jLabel6.setFont(new java.awt.Font("Padauk", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("./GreyX");

        javax.swing.GroupLayout headerSidePanelLayout = new javax.swing.GroupLayout(headerSidePanel);
        headerSidePanel.setLayout(headerSidePanelLayout);
        headerSidePanelLayout.setHorizontalGroup(
            headerSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(headerSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerSidePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        headerSidePanelLayout.setVerticalGroup(
            headerSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(headerSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerSidePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purpleSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cyanSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orangeSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pinkSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(headerSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purpleSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinkSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orangeSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cyanSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backgroundChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backgroundChange, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(backPanel, "card2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purpleSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpleSidePanelMouseClicked
        // TODO add your handling code here:
        
        gantiWarna(purpleMainPanel);
    }//GEN-LAST:event_purpleSidePanelMouseClicked

    private void orangeSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orangeSidePanelMouseClicked
        // TODO add your handling code here:
        
        gantiWarna(orangeMainPanel);
    }//GEN-LAST:event_orangeSidePanelMouseClicked

    private void cyanSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cyanSidePanelMouseClicked
        // TODO add your handling code here:
        
        gantiWarna(cyanMainPanel);
    }//GEN-LAST:event_cyanSidePanelMouseClicked

    private void purpleSidePanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_purpleSidePanelFocusGained

    }//GEN-LAST:event_purpleSidePanelFocusGained

    private void pinkSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinkSidePanelMouseClicked
        // TODO add your handling code here:
        
        gantiWarna(pinkMainPanel);
        
    }//GEN-LAST:event_pinkSidePanelMouseClicked

    private void purpleSidePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpleSidePanelMouseEntered
        // TODO add your handling code here:
        
        rubah(purpleSidePanel,purpleMainPanel);

    }//GEN-LAST:event_purpleSidePanelMouseEntered

    private void purpleSidePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpleSidePanelMouseExited
        // TODO add your handling code here:
        
        balik(purpleSidePanel);
    }//GEN-LAST:event_purpleSidePanelMouseExited

    private void pinkSidePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinkSidePanelMouseEntered
        // TODO add your handling code here:
        
        rubah(pinkSidePanel,pinkMainPanel);
    }//GEN-LAST:event_pinkSidePanelMouseEntered

    private void pinkSidePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinkSidePanelMouseExited
        // TODO add your handling code here:
        balik(pinkSidePanel);
    }//GEN-LAST:event_pinkSidePanelMouseExited

    private void orangeSidePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orangeSidePanelMouseEntered
        // TODO add your handling code here:
        
        rubah(orangeSidePanel,orangeMainPanel);
    }//GEN-LAST:event_orangeSidePanelMouseEntered

    private void orangeSidePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orangeSidePanelMouseExited
        // TODO add your handling code here:
        
        balik(orangeSidePanel);
    }//GEN-LAST:event_orangeSidePanelMouseExited

    private void cyanSidePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cyanSidePanelMouseEntered
        // TODO add your handling code here:
        
        rubah(cyanSidePanel,cyanMainPanel);
    }//GEN-LAST:event_cyanSidePanelMouseEntered

    private void cyanSidePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cyanSidePanelMouseExited
        // TODO add your handling code here:
        balik(cyanSidePanel);
    }//GEN-LAST:event_cyanSidePanelMouseExited

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    void gantiWarna(Component cmp){
        
        //remove
        backgroundChange.removeAll();
        backgroundChange.repaint();
        backgroundChange.revalidate();
        
        //add
        backgroundChange.add(cmp);
        backgroundChange.repaint();
        backgroundChange.revalidate();
    }
    void balik(Component cmp){
//        get color
        Color color = sidePanel.getBackground();
        
//        set color
        cmp.setBackground(color);
    }
    void rubah(Component cmp1,Component cmp2){
//        get color
        Color color = cmp2.getBackground();
        
//        set color
        cmp1.setBackground(color);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JPanel backgroundChange;
    private javax.swing.JPanel cyanMainPanel;
    private javax.swing.JPanel cyanSidePanel;
    private javax.swing.JPanel headerSidePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel orangeMainPanel;
    private javax.swing.JPanel orangeSidePanel;
    private javax.swing.JPanel pinkMainPanel;
    private javax.swing.JPanel pinkSidePanel;
    private javax.swing.JPanel purpleMainPanel;
    private javax.swing.JPanel purpleSidePanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}

